site_name: 'goappdemo4'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/Team-DX-22/goappdemo4
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
